# Generated by Django 5.2.7 on 2025-10-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="view",
        ),
        migrations.AddField(
            model_name="video",
            name="number_of_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
