# Generated by Django 5.2.7 on 2025-10-20 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_video_view_video_number_of_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="upload_time",
            new_name="uploaded_at",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="user",
            new_name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="video",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="video",
            name="number_of_views",
        ),
        migrations.AddField(
            model_name="video",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="disliked_videos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_videos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
