# Generated by Django 5.2.7 on 2025-10-20 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_upload_time_video_uploaded_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="uploaded_at",
            new_name="upload_time",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="uploaded_by",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="video",
            name="views",
        ),
        migrations.AddField(
            model_name="video",
            name="channel",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.channel"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="view",
            field=models.ManyToManyField(
                blank=True, related_name="video_view", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="video_dislike", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="video_like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                default="images/default_video_thumbnail.png", upload_to="images/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
