# Generated by Django 5.2.7 on 2025-10-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_comment_parent_alter_comment_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
